// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fragrances.sql

package database

import (
	"context"
)

const addFragrance = `-- name: AddFragrance :one
INSERT INTO fragrances (brand, name)
VALUES (
    $1,
    $2
)
RETURNING id, brand, name
`

type AddFragranceParams struct {
	Brand string
	Name  string
}

func (q *Queries) AddFragrance(ctx context.Context, arg AddFragranceParams) (Fragrance, error) {
	row := q.db.QueryRowContext(ctx, addFragrance, arg.Brand, arg.Name)
	var i Fragrance
	err := row.Scan(&i.ID, &i.Brand, &i.Name)
	return i, err
}

const getFragrance = `-- name: GetFragrance :one
SELECT id, brand, name 
FROM fragrances 
WHERE brand = $1 AND name = $2
`

type GetFragranceParams struct {
	Brand string
	Name  string
}

func (q *Queries) GetFragrance(ctx context.Context, arg GetFragranceParams) (Fragrance, error) {
	row := q.db.QueryRowContext(ctx, getFragrance, arg.Brand, arg.Name)
	var i Fragrance
	err := row.Scan(&i.ID, &i.Brand, &i.Name)
	return i, err
}

const getFragrances = `-- name: GetFragrances :many
SELECT id, brand, name FROM fragrances
`

func (q *Queries) GetFragrances(ctx context.Context) ([]Fragrance, error) {
	rows, err := q.db.QueryContext(ctx, getFragrances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Fragrance
	for rows.Next() {
		var i Fragrance
		if err := rows.Scan(&i.ID, &i.Brand, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFragrance = `-- name: RemoveFragrance :one
DELETE FROM fragrances WHERE id = $1
RETURNING id, brand, name
`

func (q *Queries) RemoveFragrance(ctx context.Context, id int32) (Fragrance, error) {
	row := q.db.QueryRowContext(ctx, removeFragrance, id)
	var i Fragrance
	err := row.Scan(&i.ID, &i.Brand, &i.Name)
	return i, err
}

const resetFragrances = `-- name: ResetFragrances :exec
DELETE FROM fragrances
`

func (q *Queries) ResetFragrances(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFragrances)
	return err
}

const updateFragrance = `-- name: UpdateFragrance :one
UPDATE fragrances 
SET brand = $2, name = $3
WHERE id = $1
RETURNING id, brand, name
`

type UpdateFragranceParams struct {
	ID    int32
	Brand string
	Name  string
}

func (q *Queries) UpdateFragrance(ctx context.Context, arg UpdateFragranceParams) (Fragrance, error) {
	row := q.db.QueryRowContext(ctx, updateFragrance, arg.ID, arg.Brand, arg.Name)
	var i Fragrance
	err := row.Scan(&i.ID, &i.Brand, &i.Name)
	return i, err
}
