// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addRating = `-- name: AddRating :one
INSERT INTO ratings (user_id, brand, name, rating, comment)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, brand, name, user_id, rating, comment
`

type AddRatingParams struct {
	UserID  uuid.UUID
	Brand   string
	Name    string
	Rating  sql.NullInt32
	Comment sql.NullString
}

func (q *Queries) AddRating(ctx context.Context, arg AddRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, addRating,
		arg.UserID,
		arg.Brand,
		arg.Name,
		arg.Rating,
		arg.Comment,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Name,
		&i.UserID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}

const getRating = `-- name: GetRating :one
SELECT id, brand, name, user_id, rating, comment 
FROM ratings 
WHERE user_id = $1 AND brand = $2 AND name = $3
`

type GetRatingParams struct {
	UserID uuid.UUID
	Brand  string
	Name   string
}

func (q *Queries) GetRating(ctx context.Context, arg GetRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, getRating, arg.UserID, arg.Brand, arg.Name)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Name,
		&i.UserID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}

const getRatings = `-- name: GetRatings :many
SELECT id, brand, name, user_id, rating, comment FROM ratings
WHERE user_id = $1
`

func (q *Queries) GetRatings(ctx context.Context, userID uuid.UUID) ([]Rating, error) {
	rows, err := q.db.QueryContext(ctx, getRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rating
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Name,
			&i.UserID,
			&i.Rating,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRating = `-- name: RemoveRating :one
DELETE FROM ratings 
WHERE user_id = $1 AND brand = $2 AND name = $3
RETURNING id, brand, name, user_id, rating, comment
`

type RemoveRatingParams struct {
	UserID uuid.UUID
	Brand  string
	Name   string
}

func (q *Queries) RemoveRating(ctx context.Context, arg RemoveRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, removeRating, arg.UserID, arg.Brand, arg.Name)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Name,
		&i.UserID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}

const resetRatings = `-- name: ResetRatings :exec
DELETE FROM ratings
`

func (q *Queries) ResetRatings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetRatings)
	return err
}

const updateRating = `-- name: UpdateRating :one
UPDATE ratings 
SET rating = $4, comment = $5
WHERE user_id = $1 AND brand = $2 AND name = $3
RETURNING id, brand, name, user_id, rating, comment
`

type UpdateRatingParams struct {
	UserID  uuid.UUID
	Brand   string
	Name    string
	Rating  sql.NullInt32
	Comment sql.NullString
}

func (q *Queries) UpdateRating(ctx context.Context, arg UpdateRatingParams) (Rating, error) {
	row := q.db.QueryRowContext(ctx, updateRating,
		arg.UserID,
		arg.Brand,
		arg.Name,
		arg.Rating,
		arg.Comment,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.Brand,
		&i.Name,
		&i.UserID,
		&i.Rating,
		&i.Comment,
	)
	return i, err
}
