// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fragrances.sql

package remoteDatabase

import (
	"context"
	"database/sql"
)

const searchFragrances = `-- name: SearchFragrances :many
SELECT id, brand, name, url
FROM public.fragrances
WHERE (
  SELECT bool_and( (brand || ' ' || name) ILIKE '%' || t || '%' )
  FROM unnest(regexp_split_to_array(trim($1), '\s+')) AS t
)
ORDER BY brand, name
LIMIT $2
OFFSET $3
`

type SearchFragrancesParams struct {
	Btrim  string
	Limit  int32
	Offset int32
}

type SearchFragrancesRow struct {
	ID    int64
	Brand sql.NullString
	Name  sql.NullString
	Url   sql.NullString
}

func (q *Queries) SearchFragrances(ctx context.Context, arg SearchFragrancesParams) ([]SearchFragrancesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchFragrances, arg.Btrim, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchFragrancesRow
	for rows.Next() {
		var i SearchFragrancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Brand,
			&i.Name,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
