// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package remoteDatabase

import (
	"database/sql"
)

type Fragrance struct {
	ID            int64
	Url           sql.NullString
	Name          sql.NullString
	Brand         sql.NullString
	Country       sql.NullString
	Gender        sql.NullString
	RatingValue   sql.NullString
	RatingCount   sql.NullInt32
	Year          sql.NullInt32
	TopNotes      sql.NullString
	MiddleNotes   sql.NullString
	BaseNotes     sql.NullString
	Perfumer1     sql.NullString
	Perfumer2     sql.NullString
	Accord1       sql.NullString
	Accord2       sql.NullString
	Accord3       sql.NullString
	Accord4       sql.NullString
	Accord5       sql.NullString
	FragranticaID sql.NullInt32
}
