-- +goose Up
CREATE TABLE ratings (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand TEXT NOT NULL,
    name TEXT NOT NULL,
    user_id uuid NOT NULL,
    rating INTEGER DEFAULT 0,
    comment TEXT DEFAULT ''
);

-- +goose Down
DROP TABLE ratings;