// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package localDatabase

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Rating struct {
	ID      int32
	Brand   string
	Name    string
	UserID  uuid.UUID
	Rating  sql.NullInt32
	Comment sql.NullString
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	HashedPassword string
	IsAdmin        bool
}
